# Generated by Django 6.0.3 on 2026-03-23 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_pct', models.FloatField(default=5.0)),
                ('total_tdc_earned', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='was_referred', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('total_referrals', models.IntegerField(default=0)),
                ('active_referrals', models.IntegerField(default=0)),
                ('total_commission_tdc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('this_month_tdc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_links',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend_requests',
                'unique_together': {('from_player', 'to_player')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friendships',
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
