# Generated by Django 6.0.3 on 2026-03-23 00:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, max_length=32, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=64)),
                ('avatar_emoji', models.CharField(blank=True, default='🎖️', max_length=8)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_verified', models.BooleanField(default=False)),
                ('commander_rank', models.PositiveSmallIntegerField(default=1)),
                ('commander_xp', models.BigIntegerField(default=0)),
                ('spec_path', models.CharField(choices=[('military', 'Military'), ('economic', 'Economic'), ('diplomatic', 'Diplomatic'), ('scientific', 'Scientific')], default='military', max_length=20)),
                ('wallet_address', models.CharField(blank=True, db_index=True, max_length=42)),
                ('tdc_in_game', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_tdc_purchased', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_tdc_spent', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_tdc_earned_ads', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('action_slots_max', models.PositiveSmallIntegerField(default=3)),
                ('action_slots_used', models.PositiveSmallIntegerField(default=0)),
                ('last_slot_regen_at', models.DateTimeField(blank=True, null=True)),
                ('regen_bonus_pct', models.FloatField(default=0.0)),
                ('attack_power_bonus', models.FloatField(default=0.0)),
                ('ban_status', models.CharField(choices=[('clean', 'Clean'), ('warning', 'Warning'), ('suspended', 'Suspended (temp)'), ('banned', 'Banned')], default='clean', max_length=12)),
                ('ban_reason', models.TextField(blank=True)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('anticheat_score', models.FloatField(default=0.0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_playtime_seconds', models.BigIntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('shield_until', models.DateTimeField(blank=True, null=True)),
                ('beginner_protection_until', models.DateTimeField(blank=True, null=True)),
                ('daily_shield_hours_used', models.FloatField(default=0.0)),
                ('shield_reset_date', models.DateField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=5)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('push_token', models.CharField(blank=True, max_length=512)),
                ('tutorial_completed', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=256)),
                ('platform', models.CharField(max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_devices',
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territories_owned', models.IntegerField(default=0)),
                ('max_territories_owned', models.IntegerField(default=0)),
                ('territories_captured', models.IntegerField(default=0)),
                ('territories_lost', models.IntegerField(default=0)),
                ('battles_fought', models.IntegerField(default=0)),
                ('battles_won', models.IntegerField(default=0)),
                ('battles_lost', models.IntegerField(default=0)),
                ('units_killed', models.BigIntegerField(default=0)),
                ('units_lost', models.BigIntegerField(default=0)),
                ('resources_produced', models.JSONField(default=dict)),
                ('resources_traded', models.BigIntegerField(default=0)),
                ('alliances_formed', models.IntegerField(default=0)),
                ('diplomacy_actions', models.IntegerField(default=0)),
                ('season_score', models.BigIntegerField(default=0)),
                ('season_rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_stats',
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['username'], name='players_usernam_3072ac_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['wallet_address'], name='players_wallet__3818b2_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_online', 'last_active'], name='players_is_onli_1099be_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['ban_status'], name='players_ban_sta_3d4a8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerdevice',
            unique_together={('player', 'fingerprint')},
        ),
    ]
