# Generated by Django 6.0.3 on 2026-03-23 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economy', '0001_initial'),
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPriceCache',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=16)),
                ('change_24h', models.FloatField(default=0)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crypto_price_cache',
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdi_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('tdi_staked', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('tdi_pending_withdraw', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_tdi_earned', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_tdi_withdrawn', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('external_wallet', models.CharField(blank=True, max_length=42)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crypto_wallet',
            },
        ),
        migrations.CreateModel(
            name='TDCTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Fiat Purchase'), ('ad_revenue', 'Ad Revenue'), ('reward', 'Game Reward'), ('item_purchase', 'Item Purchase'), ('withdrawal', 'Wallet Withdrawal'), ('season_reward', 'Season Reward'), ('alliance_transfer', 'Alliance Transfer'), ('refund', 'Refund')], max_length=30)),
                ('amount_tdc', models.DecimalField(decimal_places=6, max_digits=20)),
                ('amount_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=66)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('from_address', models.CharField(blank=True, max_length=42)),
                ('to_address', models.CharField(blank=True, max_length=42)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('territory_h3', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tdc_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tdc_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eur_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tdc_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('bonus_tdc', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('payment_provider', models.CharField(default='stripe', max_length=30)),
                ('payment_intent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid — Awaiting Minting'), ('minting', 'Minting on Chain'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tdc_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.tdctransaction')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TDITransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('purchase_bonus', 'TDC Purchase Bonus'), ('territory_yield', 'Territory Daily Yield'), ('stake_reward', 'Staking Reward'), ('withdraw', 'Withdrawal to External Wallet'), ('convert_to_tdc', 'Convert TDI → TDC'), ('referral_bonus', 'Referral Bonus')], max_length=30)),
                ('amount_tdi', models.DecimalField(decimal_places=8, max_digits=18)),
                ('matic_rate', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('usd_value', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdi_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tdi_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaignRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('revenue_tdc', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('player_share_tdc', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('platform_share_tdc', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('paid_out', models.BooleanField(default=False)),
                ('payout_tx', models.CharField(blank=True, max_length=66)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.adcampaign')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territories.territory')),
            ],
            options={
                'db_table': 'ad_campaign_revenue',
                'unique_together': {('territory', 'campaign', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='tdctransaction',
            index=models.Index(fields=['player', 'transaction_type'], name='tdc_transac_player__815065_idx'),
        ),
        migrations.AddIndex(
            model_name='tdctransaction',
            index=models.Index(fields=['created_at'], name='tdc_transac_created_3f3422_idx'),
        ),
        migrations.AddIndex(
            model_name='tdctransaction',
            index=models.Index(fields=['status'], name='tdc_transac_status_ef15e0_idx'),
        ),
    ]
