# Generated by Django 6.0.3 on 2026-03-23 00:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(default='🏆', max_length=10)),
                ('category', models.CharField(choices=[('territory', 'Territory'), ('combat', 'Combat'), ('economy', 'Economy'), ('social', 'Social'), ('exploration', 'Exploration'), ('streak', 'Streak'), ('tdc', 'TDC'), ('secret', 'Secret')], max_length=20)),
                ('is_hidden', models.BooleanField(default=False)),
                ('tier', models.IntegerField(default=1)),
                ('threshold', models.BigIntegerField(default=1)),
                ('reward_tdc', models.IntegerField(default=0)),
                ('reward_xp', models.IntegerField(default=0)),
                ('reward_cosmetic_code', models.CharField(blank=True, max_length=50)),
                ('reward_badge_emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['category', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='ClickerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('coin', '🪙 Coin'), ('crate', '📦 Crate'), ('bomb', '💣 Bomb - avoid'), ('multiplier', '⚡ Multiplier'), ('rare_gem', '💎 Rare Gem')], max_length=20)),
                ('base_points', models.PositiveIntegerField(default=10)),
                ('spawn_weight', models.FloatField(default=1.0)),
                ('is_avoidance', models.BooleanField(default=False)),
                ('icon_3d', models.CharField(blank=True, max_length=60)),
                ('color_hex', models.CharField(default='#FFB800', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clicker_target',
            },
        ),
        migrations.CreateModel(
            name='GameNotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('attack_incoming', 'Attack Incoming'), ('battle_resolved', 'Battle Resolved'), ('territory_lost', 'Territory Lost'), ('streak_risk', 'Streak At Risk'), ('daily_missions', 'Daily Missions Ready'), ('ad_revenue', 'Ad Revenue Earned'), ('alliance_war', 'Alliance Declared War'), ('control_tower', 'Control Tower Event'), ('rank_up', 'Commander Rank Up'), ('offline', 'Offline Resource Summary')], max_length=30)),
                ('title_template', models.CharField(max_length=100)),
                ('body_template', models.CharField(max_length=255)),
                ('priority', models.CharField(default='high', max_length=10)),
                ('ab_variant', models.CharField(default='A', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('click_through_rate', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='MissionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_type', models.CharField(choices=[('claim', 'Claim Territories'), ('win_battles', 'Win Battles'), ('produce', 'Produce Resources'), ('trade', 'Send Trade Routes'), ('visit_poi', 'Visit POI Zone'), ('alliance', 'Alliance Action'), ('spend_tdc', 'Spend TDC'), ('online', 'Online Time'), ('tower', 'Control Tower')], max_length=20)),
                ('title_template', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(default='🎯', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('target_min', models.IntegerField(default=1)),
                ('target_max', models.IntegerField(default=5)),
                ('reward_tdc_min', models.IntegerField(default=10)),
                ('reward_tdc_max', models.IntegerField(default=50)),
                ('reward_xp', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mission_templates',
            },
        ),
        migrations.CreateModel(
            name='PlayerStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('streak_shields', models.IntegerField(default=0)),
                ('total_login_days', models.IntegerField(default=0)),
                ('total_tdc_from_streaks', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('last_reward_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_streaks',
            },
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('attack', 'Attaque'), ('defense', 'Défense'), ('economy', 'Économie'), ('influence', 'Rayonnement'), ('tech', 'Technologie')], max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('effect', models.TextField()),
                ('cost_json', models.JSONField(default=list)),
                ('position', models.IntegerField(default=0)),
                ('icon', models.CharField(default='⚔️', max_length=8)),
                ('fork_group', models.CharField(blank=True, default='', max_length=40)),
                ('tradeoff_note', models.TextField(blank=True, default='')),
                ('requires_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_set', to='progression.skillnode')),
            ],
            options={
                'ordering': ['branch', 'position'],
                'unique_together': {('branch', 'position', 'fork_group')},
            },
        ),
        migrations.CreateModel(
            name='DailyClickerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('max_clicks', models.PositiveIntegerField(default=60)),
                ('score', models.BigIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=60000)),
                ('tdc_earned', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('tdi_earned', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('loot_tier', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=12)),
                ('loot_item', models.CharField(blank=True, max_length=60)),
                ('loot_quantity', models.PositiveIntegerField(default=0)),
                ('streak_mult', models.FloatField(default=1.0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicker_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_clicker_session',
                'unique_together': {('player', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySpinReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tier', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=12)),
                ('reward_type', models.CharField(max_length=30)),
                ('reward_value', models.IntegerField()),
                ('reward_description', models.CharField(max_length=200)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_spin_rewards',
                'unique_together': {('player', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('regional', 'Regional'), ('alliance', 'Alliance')], default='global', max_length=12)),
                ('region_code', models.CharField(blank=True, max_length=8)),
                ('alliance_id', models.UUIDField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField()),
                ('prev_rank', models.PositiveIntegerField(null=True)),
                ('score', models.BigIntegerField(default=0)),
                ('territories', models.PositiveIntegerField(default=0)),
                ('battles_won', models.PositiveIntegerField(default=0)),
                ('tdc_total', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard_snapshot',
                'ordering': ['rank'],
                'unique_together': {('scope', 'region_code', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('value_at_unlock', models.BigIntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progression.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_achievements',
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='PlayerDailyMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('target_count', models.IntegerField()),
                ('current_count', models.IntegerField(default=0)),
                ('reward_tdc', models.IntegerField()),
                ('reward_xp', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_missions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progression.missiontemplate')),
            ],
            options={
                'db_table': 'player_daily_missions',
                'ordering': ['-date', 'is_completed'],
                'unique_together': {('player', 'template', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progression.skillnode')),
            ],
            options={
                'unique_together': {('player', 'skill')},
            },
        ),
    ]
