# Generated by Django 6.0.3 on 2026-03-23 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaticRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('war', 'At War'), ('ceasefire', 'Ceasefire'), ('neutral', 'Neutral'), ('nap', 'Non-Aggression Pact'), ('trade', 'Trade Agreement'), ('alliance', 'Allied')], default='neutral', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('terms', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'diplomatic_relations',
            },
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(db_index=True, max_length=6, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('squad', 'Squad'), ('guild', 'Guild'), ('federation', 'Federation')], default='squad', max_length=12)),
                ('banner_color', models.CharField(default='#1D9E75', max_length=7)),
                ('banner_symbol', models.CharField(blank=True, max_length=50)),
                ('treasury_energy', models.FloatField(default=0.0)),
                ('treasury_food', models.FloatField(default=0.0)),
                ('treasury_credits', models.FloatField(default=0.0)),
                ('treasury_materials', models.FloatField(default=0.0)),
                ('treasury_tdc', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_territories', models.IntegerField(default=0)),
                ('total_members', models.IntegerField(default=1)),
                ('war_score', models.BigIntegerField(default=0)),
                ('season_score', models.BigIntegerField(default=0)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('min_rank_to_join', models.IntegerField(default=1)),
                ('require_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_alliances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alliances',
                'ordering': ['-war_score'],
            },
        ),
        migrations.CreateModel(
            name='AllianceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('officer', 'Officer'), ('veteran', 'Veteran'), ('member', 'Member'), ('recruit', 'Recruit')], default='recruit', max_length=12)),
                ('resources_contributed', models.JSONField(default=dict)),
                ('battles_fought_for_alliance', models.IntegerField(default=0)),
                ('territories_taken_for_alliance', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='alliances.alliance')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alliance_members',
            },
        ),
        migrations.CreateModel(
            name='AllianceOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=12)),
                ('min_participants', models.IntegerField(default=5)),
                ('starts_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliances.alliance')),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alliance_operations',
            },
        ),
    ]
