# Generated by Django 6.0.3 on 2026-03-23 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alliances', '0001_initial'),
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceoperation',
            name='target_territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='territories.territory'),
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomatic_initiated', to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomatic_received', to='alliances.alliance'),
        ),
        migrations.AlterUniqueTogether(
            name='diplomaticrelation',
            unique_together={('initiator', 'target')},
        ),
    ]
