# Generated by Django 6.0.3 on 2026-03-23 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('price_eur', models.DecimalField(decimal_places=2, default=4.99, max_digits=6)),
                ('price_tdc', models.DecimalField(decimal_places=2, default=499, max_digits=12)),
                ('total_tiers', models.IntegerField(default=40)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'battle_passes',
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('shield', 'Territory Shield'), ('military', 'Military Boost'), ('construction', 'Construction Speed'), ('cosmetic', 'Cosmetic'), ('battle_pass', 'Battle Pass'), ('alliance', 'Alliance Premium'), ('resource_pack', 'Resource Pack')], max_length=20)),
                ('price_tdc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('effect_type', models.CharField(max_length=50)),
                ('effect_value', models.FloatField(default=0.0)),
                ('effect_duration_seconds', models.IntegerField(default=0)),
                ('max_per_day', models.IntegerField(default=0)),
                ('hard_cap_pct', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_limited', models.BooleanField(default=False)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('max_stock', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('icon_url', models.URLField(blank=True)),
                ('rarity', models.CharField(default='common', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop_items',
                'ordering': ['category', 'price_tdc'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_email', models.EmailField(max_length=254)),
                ('campaign_name', models.CharField(max_length=200)),
                ('banner_url', models.URLField()),
                ('click_url', models.URLField()),
                ('logo_url', models.URLField(blank=True)),
                ('targeting_type', models.CharField(choices=[('global', 'Global'), ('country', 'By Country'), ('territory_type', 'By Territory Type'), ('landmark', 'Landmarks Only')], default='global', max_length=20)),
                ('target_countries', models.JSONField(default=list)),
                ('target_territory_types', models.JSONField(default=list)),
                ('min_territory_tier', models.IntegerField(default=1)),
                ('budget_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cpm_eur', models.DecimalField(decimal_places=4, default=2.0, max_digits=6)),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('target_impressions', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBattlePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('current_tier', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('claimed_tiers', models.JSONField(default=list)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.battlepass')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_battle_pass',
                'unique_together': {('player', 'battle_pass')},
            },
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='economy.shopitem')),
            ],
            options={
                'db_table': 'player_inventory',
                'unique_together': {('player', 'item')},
            },
        ),
        migrations.CreateModel(
            name='BattlePassReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('is_free_tier', models.BooleanField(default=False)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='economy.battlepass')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='economy.shopitem')),
            ],
            options={
                'db_table': 'battle_pass_rewards',
                'ordering': ['tier'],
                'unique_together': {('battle_pass', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='ActiveBoost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boost_type', models.CharField(max_length=50)),
                ('boost_value', models.FloatField()),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_boosts', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_boosts', to='territories.territory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='economy.shopitem')),
            ],
            options={
                'db_table': 'active_boosts',
                'indexes': [models.Index(fields=['player', 'boost_type'], name='active_boos_player__b3c3c7_idx'), models.Index(fields=['expires_at'], name='active_boos_expires_7a4e7f_idx')],
            },
        ),
    ]
