# Generated by Django 6.0.3 on 2026-03-23 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alliances', '0002_initial'),
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battle_type', models.CharField(choices=[('conquest', 'Conquest'), ('raid', 'Raid'), ('siege', 'Siege'), ('surprise', 'Surprise Attack')], default='conquest', max_length=20)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('active', 'Active'), ('resolving', 'Resolving'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='preparing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolves_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=10)),
                ('territory_captured', models.BooleanField(default=False)),
                ('attacker_casualties', models.JSONField(default=dict)),
                ('defender_casualties', models.JSONField(default=dict)),
                ('resources_looted', models.JSONField(default=dict)),
                ('combat_log', models.JSONField(default=list)),
                ('alliance_assault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliances.allianceoperation')),
                ('defender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defensive_battles', to=settings.AUTH_USER_MODEL)),
                ('target_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='territories.territory')),
            ],
            options={
                'db_table': 'battles',
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('attacker', 'Attacker'), ('defender', 'Defender')], max_length=10)),
                ('units_deployed', models.JSONField(default=dict)),
                ('units_survived', models.JSONField(default=dict)),
                ('units_lost', models.JSONField(default=dict)),
                ('resources_contributed', models.JSONField(default=dict)),
                ('resources_gained', models.JSONField(default=dict)),
                ('xp_earned', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_commander', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='combat.battle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'battle_participants',
            },
        ),
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('artillery', 'Artillery'), ('air', 'Air Support'), ('naval', 'Naval')], max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('garrison', 'Garrisoned'), ('marching', 'Marching'), ('besieging', 'Besieging'), ('recovering', 'Recovering')], default='garrison', max_length=20)),
                ('morale', models.FloatField(default=100.0)),
                ('boost_pct', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garrisoned_units', to='territories.territory')),
            ],
            options={
                'db_table': 'military_units',
            },
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status'], name='battles_status_fde8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['resolves_at'], name='battles_resolve_384ab3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battleparticipant',
            unique_together={('battle', 'player')},
        ),
        migrations.AddIndex(
            model_name='militaryunit',
            index=models.Index(fields=['player', 'unit_type'], name='military_un_player__978c17_idx'),
        ),
        migrations.AddIndex(
            model_name='militaryunit',
            index=models.Index(fields=['territory'], name='military_un_territo_253687_idx'),
        ),
    ]
